def exception_handler(exception_type, exception, traceback):
    print("%s: %s" % (exception_type.__name__, exception))

